disabled_rules:
- trailing_whitespace
- large_tuple
- empty_count
opt_in_rules:
- empty_count
- empty_string
identifier_name:
    validates_start_with_lowercase: false
    allowed_symbols: "_"
    excluded:
        - id
        - i 
        - j
        - k
        - a
        - b
        - x
        - y 
        - z
        - t
        - u 
        - v
        - v0
        - v1
        - v2
        - v3
        - v4
        - v5
line_length:
    warning: 150
    error: 1000
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 10
    error: 20
type_body_length:
    warning: 700
    error: 800
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
reporter: "xcode"